version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: item
      POSTGRES_PASSWORD: item
      POSTGRES_DB: items
    volumes:
      - ./data:/var/lib/postgresql/data
